const destinaionSeedData = [
    { "destination_name": "Yangon", "destination": "yangon", "state_region": "Yangon Region", "country": "Myanmar", "score": 0 },
    { "destination_name": "Mandalay", "destination": "mandalay", "state_region": "Mandalay Region", "country": "Myanmar", "score": 0 },
    { "destination_name": "Naypyidaw", "destination": "naypyidaw", "state_region": "Naypyidaw Union Territory", "country": "Myanmar", "score": 0 },
    { "destination_name": "Bagan", "destination": "bagan", "state_region": "Mandalay Region", "country": "Myanmar", "score": 0 },
    { "destination_name": "Inle Lake", "destination": "inle_lake", "state_region": "Shan State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Pyin Oo Lwin", "destination": "pyin_oo_lwin", "state_region": "Mandalay Region", "country": "Myanmar", "score": 0 },
    { "destination_name": "Kalaw", "destination": "kalaw", "state_region": "Shan State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Hsipaw", "destination": "hsipaw", "state_region": "Shan State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Mrauk U", "destination": "mrauk_u", "state_region": "Rakhine State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Ngapali", "destination": "ngapali", "state_region": "Rakhine State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Kyaiktiyo", "destination": "kyaiktiyo", "state_region": "Mon State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Taunggyi", "destination": "taunggyi", "state_region": "Shan State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Loikaw", "destination": "loikaw", "state_region": "Kayah State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Hpa-An", "destination": "hpa_an", "state_region": "Kayin State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Kyaing Tong", "destination": "kyaing_tong", "state_region": "Shan State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Myitkyina", "destination": "myitkyina", "state_region": "Kachin State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Myeik", "destination": "myeik", "state_region": "Tanintharyi Region", "country": "Myanmar", "score": 0 },
    { "destination_name": "Dawei", "destination": "dawei", "state_region": "Tanintharyi Region", "country": "Myanmar", "score": 0 },
    { "destination_name": "Pathein", "destination": "pathein", "state_region": "Ayeyarwady Region", "country": "Myanmar", "score": 0 },
    { "destination_name": "Sittwe", "destination": "sittwe", "state_region": "Rakhine State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Mawlamyine", "destination": "mawlamyine", "state_region": "Mon State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Bago", "destination": "bago", "state_region": "Bago Region", "country": "Myanmar", "score": 0 },
    { "destination_name": "Pyay", "destination": "pyay", "state_region": "Bago Region", "country": "Myanmar", "score": 0 },
    { "destination_name": "Meiktila", "destination": "meiktila", "state_region": "Mandalay Region", "country": "Myanmar", "score": 0 },
    { "destination_name": "Magway", "destination": "magway", "state_region": "Magway Region", "country": "Myanmar", "score": 0 },
    { "destination_name": "Sagaing", "destination": "sagaing", "state_region": "Sagaing Region", "country": "Myanmar", "score": 0 },
    { "destination_name": "Shwebo", "destination": "shwebo", "state_region": "Sagaing Region", "country": "Myanmar", "score": 0 },
    { "destination_name": "Monywa", "destination": "monywa", "state_region": "Sagaing Region", "country": "Myanmar", "score": 0 },
    { "destination_name": "Lashio", "destination": "lashio", "state_region": "Shan State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Muse", "destination": "muse", "state_region": "Shan State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Kengtung", "destination": "kengtung", "state_region": "Shan State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Tachileik", "destination": "tachileik", "state_region": "Shan State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Bhamo", "destination": "bhamo", "state_region": "Kachin State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Putao", "destination": "putao", "state_region": "Kachin State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Hakha", "destination": "hakha", "state_region": "Chin State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Falam", "destination": "falam", "state_region": "Chin State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Tiddim", "destination": "tiddim", "state_region": "Chin State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Mindat", "destination": "mindat", "state_region": "Chin State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Kanpetlet", "destination": "kanpetlet", "state_region": "Chin State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Kyaukme", "destination": "kyaukme", "state_region": "Shan State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Thandwe", "destination": "thandwe", "state_region": "Rakhine State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Maungdaw", "destination": "maungdaw", "state_region": "Rakhine State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Ponnagyun", "destination": "ponnagyun", "state_region": "Rakhine State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Kyaukpyu", "destination": "kyaukpyu", "state_region": "Rakhine State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Ann", "destination": "ann", "state_region": "Rakhine State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Minbya", "destination": "minbya", "state_region": "Rakhine State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Pauktaw", "destination": "pauktaw", "state_region": "Rakhine State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Myebon", "destination": "myebon", "state_region": "Rakhine State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Thayetchaung", "destination": "thayetchaung", "state_region": "Kayin State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Hpapun", "destination": "hpapun", "state_region": "Kayin State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Pindaya", "destination": "pindaya", "state_region": "Shan State", "country": "Myanmar", "score": 0 },
    { "destination_name": "Kalaw", "destination": "kalaw", "state_region": "Shan State", "country": "Myanmar", "score": 0 }
]

export default destinaionSeedData;
